//
// AcceptConnectionInvitationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AcceptConnectionInvitationRequest: Codable {
    /// The base64-encoded raw invitation.
    public var invitation: String

    public init(invitation: String) {
        self.invitation = invitation
    }
}
