//
// Arr.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Arr: Codable {
    public var elements: [Any]?

    public init(elements: [Any]? = nil) {
        self.elements = elements
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case elements
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        elements = try container.decodeIfPresent([Any].self, forKey: .elements)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let elements = elements {
            try container.encodeIfPresent(try JSONSerialization.data(withJSONObject: elements), forKey: .elements)
        }
    }
}
