//
// CreateConnectionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateConnectionRequest: Codable {
    /// A human readable alias for the connection.
    public var label: String?

    public init(label: String? = nil) {
        self.label = label
    }
}
