//
// CreateManagedDIDResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateManagedDIDResponse: Codable {
    /// A long-form DID for the created DID
    public var longFormDid: String

    public init(longFormDid: String) {
        self.longFormDid = longFormDid
    }
}
