//
// DIDOperationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DIDOperationResponse: Codable {
    public var scheduledOperation: DidOperationSubmission

    public init(scheduledOperation: DidOperationSubmission) {
        self.scheduledOperation = scheduledOperation
    }
}
