//
// ManagedDIDKeyTemplate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// key-pair template to add to DID document. 
public struct ManagedDIDKeyTemplate: Codable {
    /// Identifier of a verification material in the DID Document
    public var id: String
    public var purpose: Purpose

    public init(id: String, purpose: Purpose) {
        self.id = id
        self.purpose = purpose
    }
}
