//
// ModelBool.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModelBool: Codable {
    public var value: Bool

    public init(value: Bool) {
        self.value = value
    }
}
