//
// Num.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Num: Codable {
    public var value: Double

    public init(value: Double) {
        self.value = value
    }
}
