//
// PatchContextAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PatchContextAction: Codable {
    public var contexts: [String]?

    public init(contexts: [String]? = nil) {
        self.contexts = contexts
    }
}
