//
// PresentationStatusPage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PresentationStatusPage: Codable {
    /// A sequence of Presentation objects.
    public var contents: [PresentationStatus]?
    /// The reference to the presentation collection itself.
    public var _self: String
    /// The type of object returned. In this case a `Collection`.
    public var kind: String
    /// Page number within the context of paginated response.
    public var pageOf: String
    /// URL of the next page (if available)
    public var next: String?
    /// URL of the previous page (if available)
    public var previous: String?

    public init(contents: [PresentationStatus]? = nil, _self: String, kind: String, pageOf: String, next: String? = nil, previous: String? = nil) {
        self.contents = contents
        self._self = _self
        self.kind = kind
        self.pageOf = pageOf
        self.next = next
        self.previous = previous
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contents
        case _self = "self"
        case kind
        case pageOf
        case next
        case previous
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        contents = try container.decodeIfPresent([PresentationStatus].self, forKey: .contents)
        _self = try container.decode(String.self, forKey: ._self)
        kind = try container.decode(String.self, forKey: .kind)
        pageOf = try container.decode(String.self, forKey: .pageOf)
        next = try container.decodeIfPresent(String.self, forKey: .next)
        previous = try container.decodeIfPresent(String.self, forKey: .previous)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(contents, forKey: .contents)
        try container.encode(_self, forKey: ._self)
        try container.encode(kind, forKey: .kind)
        try container.encode(pageOf, forKey: .pageOf)
        try container.encodeIfPresent(next, forKey: .next)
        try container.encodeIfPresent(previous, forKey: .previous)
    }
}
