//
// ProofRequestAux.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProofRequestAux: Codable {
    /// The unique identifier of a schema the VC should comply with.
    public var schemaId: String
    /// One or more issuers that are trusted by the verifier emitting the proof presentation request.
    public var trustIssuers: [String]?

    public init(schemaId: String, trustIssuers: [String]? = nil) {
        self.schemaId = schemaId
        self.trustIssuers = trustIssuers
    }
}
