//
// Purpose.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Purpose of the verification material in the DID Document 
public enum Purpose: String, Codable, CaseIterable {
    case assertionmethod = "assertionMethod"
    case authentication = "authentication"
    case capabilitydelegation = "capabilityDelegation"
    case capabilityinvocation = "capabilityInvocation"
    case keyagreement = "keyAgreement"
}
