//
// RequestPresentationInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RequestPresentationInput: Codable {
    /// The unique identifier of an established connection between the verifier and the prover.
    public var connectionId: String
    public var options: Options?
    /// The type of proofs requested in the context of this proof presentation request (e.g., VC schema, trusted issuers, etc.)
    public var proofs: [ProofRequestAux]?

    public init(connectionId: String, options: Options? = nil, proofs: [ProofRequestAux]? = nil) {
        self.connectionId = connectionId
        self.options = options
        self.proofs = proofs
    }
}
