//
// Service.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// A service expressed in the DID document. https://www.w3.org/TR/did-core/#services 
public struct Service: Codable {
    /// The id of the service. Requires a URI fragment when use in create / update DID. Returns the full ID (with DID prefix) when resolving DID
    public var id: String
    public var type: ServiceType
    public var serviceEndpoint: Json

    public init(id: String, type: ServiceType, serviceEndpoint: Json) {
        self.id = id
        self.type = type
        self.serviceEndpoint = serviceEndpoint
    }
}
