//
// UpdateManagedDIDServiceAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// A patch to existing Service. &#39;type&#39; and &#39;serviceEndpoint&#39; cannot both be empty. 
public struct UpdateManagedDIDServiceAction: Codable {
    /// The id of the service to update
    public var id: String
    public var type: UpdateManagedDIDServiceActionType?
    public var serviceEndpoint: Json?

    public init(id: String, type: UpdateManagedDIDServiceActionType? = nil, serviceEndpoint: Json? = nil) {
        self.id = id
        self.type = type
        self.serviceEndpoint = serviceEndpoint
    }
}
