//
// VerificationPolicyInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VerificationPolicyInput: Codable {
    public var id: UUID?
    public var name: String
    public var description: String
    public var constraints: [VerificationPolicyConstraint]?

    public init(id: UUID? = nil, name: String, description: String, constraints: [VerificationPolicyConstraint]? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.constraints = constraints
    }
}
