//
// AcceptCredentialOfferRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AcceptCredentialOfferRequest: Codable {
    /// The short-form subject Prism DID to which the verifiable credential should be issued.
    public var subjectId: String

    public init(subjectId: String) {
        self.subjectId = subjectId
    }
}
