//
// ActionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ActionType: String, Codable, CaseIterable {
    case addKey = "ADD_KEY"
    case addService = "ADD_SERVICE"
    case patchContext = "PATCH_CONTEXT"
    case removeKey = "REMOVE_KEY"
    case removeService = "REMOVE_SERVICE"
    case updateService = "UPDATE_SERVICE"
}
