//
// ConnectionInvitation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// The invitation for this connection 
public struct ConnectionInvitation: Codable {
    /// The unique identifier of the invitation. It should be used as parent thread ID (pthid) for the Connection Request message that follows.
    public var id: UUID
    /// The DIDComm Message Type URI (MTURI) the invitation message complies with.
    public var type: String
    /// The DID representing the sender to be used by recipients for future interactions.
    public var from: String
    /// The invitation message encoded as a URL. This URL follows the Out of [Band 2.0 protocol](https://identity.foundation/didcomm-messaging/spec/v2.0/#out-of-band-messages) and can be used to generate a QR code for example.
    public var invitationUrl: String

    public init(id: UUID, type: String, from: String, invitationUrl: String) {
        self.id = id
        self.type = type
        self.from = from
        self.invitationUrl = invitationUrl
    }
}
