//
// CreateManagedDidRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateManagedDidRequest: Codable {
    public var documentTemplate: CreateManagedDidRequestDocumentTemplate

    public init(documentTemplate: CreateManagedDidRequestDocumentTemplate) {
        self.documentTemplate = documentTemplate
    }
}
