//
// CreateManagedDidRequestDocumentTemplate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateManagedDidRequestDocumentTemplate: Codable {
    public var publicKeys: [ManagedDIDKeyTemplate]?
    public var services: [Service]?
    public var contexts: [String]?

    public init(publicKeys: [ManagedDIDKeyTemplate]? = nil, services: [Service]? = nil, contexts: [String]? = nil) {
        self.publicKeys = publicKeys
        self.services = services
        self.contexts = contexts
    }
}
