//
// DIDDocumentMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// [DID document metadata](https://www.w3.org/TR/did-core/#did-document-metadata) 
public struct DIDDocumentMetadata: Codable {
    /// If a DID has been deactivated, DID document metadata MUST include this property with the boolean value true. If a DID has not been deactivated, this property is OPTIONAL, but if included, MUST have the boolean value false.
    public var deactivated: Bool?
    ///  A DID in canonical form. If a DID is in long form and has been published, DID document metadata MUST contain a `canonicalId`` property with the short form DID as its value. If a DID in short form or has not been published, DID document metadata MUST NOT contain a `canonicalId` property. 
    public var canonicalId: String?
    ///  DID document metadata MUST contain a versionId property with the hash of the AtalaOperation contained in the latest valid SignedAtalaOperation that created the DID or changed the DID's internal state. 
    public var versionId: String?
    /// The timestamp of the Cardano block that contained the first valid SignedAtalaOperation with a CreateDIDOperation that created the DID.
    public var created: String?
    /// The timestamp of the Cardano block that contained the latest valid SignedAtalaOperation that changed the DID's internal state.
    public var updated: String?

    public init(deactivated: Bool? = nil, canonicalId: String? = nil, versionId: String? = nil, created: String? = nil, updated: String? = nil) {
        self.deactivated = deactivated
        self.canonicalId = canonicalId
        self.versionId = versionId
        self.created = created
        self.updated = updated
    }
}
