//
// DidOperationSubmission.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DidOperationSubmission: Codable {
    /// A scheduled operation ID
    public var id: String
    /// A DID affected by the scheduled operation
    public var didRef: String

    public init(id: String, didRef: String) {
        self.id = id
        self.didRef = didRef
    }
}
