//
// ErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ErrorResponse: Codable {
    /// The HTTP status code for this occurrence of the problem.
    public var status: Int
    /// A URI reference that identifies the problem type.
    public var type: String
    /// A short, human-readable summary of the problem type. It does not change from occurrence to occurrence of the problem.
    public var title: String
    /// A human-readable explanation specific to this occurrence of the problem.
    public var detail: String?
    /// A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
    public var instance: String

    public init(status: Int, type: String, title: String, detail: String? = nil, instance: String) {
        self.status = status
        self.type = type
        self.title = title
        self.detail = detail
        self.instance = instance
    }
}
