//
// HealthInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HealthInfo: Codable {
    /// The semantic version number of the running service
    public var version: String

    public init(version: String) {
        self.version = version
    }
}
