//
// ManagedDIDPage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ManagedDIDPage: Codable {
    public var _self: String
    public var kind: String
    public var pageOf: String
    public var next: String?
    public var previous: String?
    public var contents: [ManagedDID]?

    public init(_self: String, kind: String, pageOf: String, next: String? = nil, previous: String? = nil, contents: [ManagedDID]? = nil) {
        self._self = _self
        self.kind = kind
        self.pageOf = pageOf
        self.next = next
        self.previous = previous
        self.contents = contents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _self = "self"
        case kind
        case pageOf
        case next
        case previous
        case contents
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        _self = try container.decode(String.self, forKey: ._self)
        kind = try container.decode(String.self, forKey: .kind)
        pageOf = try container.decode(String.self, forKey: .pageOf)
        next = try container.decodeIfPresent(String.self, forKey: .next)
        previous = try container.decodeIfPresent(String.self, forKey: .previous)
        contents = try container.decodeIfPresent([ManagedDID].self, forKey: .contents)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(_self, forKey: ._self)
        try container.encode(kind, forKey: .kind)
        try container.encode(pageOf, forKey: .pageOf)
        try container.encodeIfPresent(next, forKey: .next)
        try container.encodeIfPresent(previous, forKey: .previous)
        try container.encodeIfPresent(contents, forKey: .contents)
    }
}
