//
// ManagedDID.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ManagedDID: Codable {
    /// A managed DID
    public var did: String
    /// A long-form DID. Mandatory when status is not PUBLISHED and optional when status is PUBLISHED
    public var longFormDid: String?
    /// A status indicating a publication state of a DID in the wallet (e.g. PUBLICATION_PENDING, PUBLISHED). Does not represent DID a full lifecyle (e.g. deactivated, recovered, updated).
    public var status: String

    public init(did: String, longFormDid: String? = nil, status: String) {
        self.did = did
        self.longFormDid = longFormDid
        self.status = status
    }
}
