//
// Options.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// The options to use when creating the proof presentation request (e.g., domain, challenge). 
public struct Options: Codable {
    /// The challenge should be a randomly generated string.
    public var challenge: String
    /// The domain value can be any string or URI.
    public var domain: String

    public init(challenge: String, domain: String) {
        self.challenge = challenge
        self.domain = domain
    }
}
