//
// PublicKeyJwk.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PublicKeyJwk: Codable {
    public var crv: String?
    public var x: String?
    public var y: String?
    public var kty: String

    public init(crv: String? = nil, x: String? = nil, y: String? = nil, kty: String) {
        self.crv = crv
        self.x = x
        self.y = y
        self.kty = kty
    }
}
