//
// UpdateManagedDIDRequestAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// A list of actions to perform on DID document. The field &#x60;addKey&#x60;, &#x60;removeKey&#x60;, &#x60;addService&#x60;, &#x60;removeService&#x60;, &#x60;updateService&#x60;, &#x60;patchContext&#x60; must corresponds to the &#x60;actionType&#x60; specified. For example, &#x60;addKey&#x60; must be present when &#x60;actionType&#x60; is &#x60;ADD_KEY&#x60;. 
public struct UpdateManagedDIDRequestAction: Codable {
    public var actionType: ActionType
    public var addKey: ManagedDIDKeyTemplate?
    public var removeKey: RemoveEntryById?
    public var addService: Service?
    public var removeService: RemoveEntryById?
    public var updateService: UpdateManagedDIDServiceAction?
    public var patchContext: PatchContextAction?

    public init(actionType: ActionType, addKey: ManagedDIDKeyTemplate? = nil, removeKey: RemoveEntryById? = nil, addService: Service? = nil, removeService: RemoveEntryById? = nil, updateService: UpdateManagedDIDServiceAction? = nil, patchContext: PatchContextAction? = nil) {
        self.actionType = actionType
        self.addKey = addKey
        self.removeKey = removeKey
        self.addService = addService
        self.removeService = removeService
        self.updateService = updateService
        self.patchContext = patchContext
    }
}
