//
// UpdateManagedDIDRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateManagedDIDRequest: Codable {
    public var actions: [UpdateManagedDIDRequestAction]?

    public init(actions: [UpdateManagedDIDRequestAction]? = nil) {
        self.actions = actions
    }
}
