//
// VerificationMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// A cryptographic public key expressed in the DID document. https://www.w3.org/TR/did-core/#verification-methods 
public struct VerificationMethod: Codable {
    /// The identifier for the verification method.
    public var id: String
    /// The type of the verification method.
    public var type: String
    /// The DID that controls the verification method.
    public var controller: String
    public var publicKeyJwk: PublicKeyJwk

    public init(id: String, type: String, controller: String, publicKeyJwk: PublicKeyJwk) {
        self.id = id
        self.type = type
        self.controller = controller
        self.publicKeyJwk = publicKeyJwk
    }
}
